//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ĐỒÁN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_BCDS
    {
        public string MaBCDS { get; set; }
        public string MaHieuXe { get; set; }
        public Nullable<int> SoLuotSua { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public string TiLe { get; set; }
    
        public virtual BAOCAODOANHSO BAOCAODOANHSO { get; set; }
        public virtual HIEUXE HIEUXE { get; set; }
    }
}
