//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ĐỒÁN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_SUDUNGVATTU
    {
        public string Ma_CTPSC { get; set; }
        public string MaVatTu { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual VATTU VATTU { get; set; }
    }
}
