//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarageManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_BCDS
    {
        public int MaBCDS { get; set; }
        public int MaHieuXe { get; set; }
        public Nullable<int> SoLuotSua { get; set; }
        public Nullable<long> ThanhTien { get; set; }
    
        public virtual BAOCAODOANHSO BAOCAODOANHSO { get; set; }
        public virtual HIEUXE HIEUXE { get; set; }
    }
}
