//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarageManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_PSC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CT_PSC()
        {
            this.CT_SUDUNGVATTU = new HashSet<CT_SUDUNGVATTU>();
        }
    
        public int MaCTPSC { get; set; }
        public Nullable<int> MaPhieuSC { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> SoLan { get; set; }
        public Nullable<int> MaTienCong { get; set; }
        public Nullable<long> ThanhTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_SUDUNGVATTU> CT_SUDUNGVATTU { get; set; }
        public virtual PHIEUSUACHUA PHIEUSUACHUA { get; set; }
        public virtual TIENCONG TIENCONG { get; set; }
    }
}
