//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarageManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_SUDUNGVATTU
    {
        public int MaCTPSC { get; set; }
        public int MaVatTu { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<long> DonGia { get; set; }
        public Nullable<long> ThanhTien { get; set; }
    
        public virtual CT_PSC CT_PSC { get; set; }
        public virtual VATTU VATTU { get; set; }
    }
}
