//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarageManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUSUACHUA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUSUACHUA()
        {
            this.CT_PSC = new HashSet<CT_PSC>();
        }
    
        public int MaPhieuSC { get; set; }
        public string BienSo { get; set; }
        public Nullable<System.DateTime> NgaySuaChua { get; set; }
        public Nullable<long> TongTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PSC> CT_PSC { get; set; }
        public virtual XE XE { get; set; }
    }
}
