//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarageManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        public int MaTaiKhoan { get; set; }
        public string HoTen { get; set; }
        public string GioiTinh { get; set; }
        public string TenTaiKhoan { get; set; }
        public string Email { get; set; }
        public string MatKhau { get; set; }
        public Nullable<int> QuyenHan { get; set; }
    
        public virtual VAITRO VAITRO { get; set; }
    }
}
