//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarageManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMSO
    {
        public Nullable<bool> TienNo { get; set; }
        public Nullable<int> SoSuaChua { get; set; }
        public int SoHieuXe { get; set; }
        public Nullable<int> SoVatTu { get; set; }
        public Nullable<int> SoTienCong { get; set; }
    }
}
