//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarageManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VATTU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VATTU()
        {
            this.BAOCAOTONs = new HashSet<BAOCAOTON>();
            this.CT_PNVT = new HashSet<CT_PNVT>();
            this.CT_SUDUNGVATTU = new HashSet<CT_SUDUNGVATTU>();
        }
    
        public int MaVatTu { get; set; }
        public string TenVatTu { get; set; }
        public Nullable<long> DonGiaHienTai { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAOCAOTON> BAOCAOTONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PNVT> CT_PNVT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_SUDUNGVATTU> CT_SUDUNGVATTU { get; set; }
    }
}
